name: workflow
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::bwa-mem2=2.2.1
  - bioconda::samtools=1.12
  - conda-forge::gsl=2.7
  - bioconda::bcftools=1.14
  - bioconda::lofreq=2.1.5
  - cyvcf2=0.30.14
  - pandas=1.3.3
  - pysam=0.19.1
  - pybedtools=0.9.0